config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trip_locations, only: [:create,:update,:destroy]
  # resources :comments  FOR FUTURE USE
  resources :locations, only: [:index,:create]
  # resources :users, only: []

  resources :users, only: [:show,:new,:create] do
  # resources :users do
    resources :trips, only: [:index,:new]
  end
  resources :trips, only: [:index,:show,:edit,:update,:new,:create,:destroy]

  root 'sessions#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post '/logout' => 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :user
    has_many :trip_locations
    has_many :locations, through: :trip_locations

    # METHOD FOR DISPLAY OF FORMATTED TRIP CREATED_AT WHEN NO NAME IS RECORDED
    def disp_name
        if self.name == ""
            t = self.created_at.to_datetime
            "#{t.month}#{t.day}#{t.year} #{t.strftime("%k:%M")}" 
        else
            self.name
        end
    end
    
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_logged_in

    # INDEX PAGE OF ALL TRIPS BY USER, DEMO ONLY
    def index
        @trips = current_user.trips
    end

    # NEW TRIP
    def new
        if params[:user_id].to_i == current_user.id
            @trip = Trip.new
            @trip.locations.build(business_name: "blank")
        else
            if params[:user_id]
                flash[:error] = "User not authorized to other user resources."
                redirect_to "/"
            else
                redirect_to "/users/#{current_user.id}/trips/new"
            end
        end
    end

    # SHOW ALL TRIPS FOR LOGGED IN USER
    def show
        @trip = Trip.find_by(id: params[:id])
        if !@trip.nil?
            @locations = Location.all
            @location = Location.new
            if current_user.id != @trip.user_id
                flash[:error] = "User not authorized to view other user resources."
                redirect_to "/"
            end
        else
            flash[:error] = "Trip ID invalid."
            redirect_to user_path(current_user)
        end        
    end

    # EDIT EXISTING TRIP (NAME ONLY)
    def edit
        @trip = Trip.find_by(id: params[:id])
    end
    
    # CREATE NEW TRIP FROM FORM AND ASSOCIATE A NEW LOCATION
    def create
        if trip_params[:locations][:address].strip == ""
            flash[:error] = "Address can not be blank."
            redirect_to "#{user_path(current_user)}#{new_trip_path}"
        else
            @location = Location.find_or_create_by(address: trip_params[:locations][:address]) do |u|
                u.user_id = current_user.id
            end
            @trip = current_user.trips.create(name: trip_params[:name])
            @trip.trip_locations.create(location_id: @location.id)
            redirect_to trip_path(@trip)
        end
    end

    # USER UPDATE NAME OF TRIP
    def update
        @trip = current_user.trips.find_by(id: params[:id])
        @trip.update(trip_params)
        redirect_to trip_path(@trip)
    end

    # DELETE EXISTING TRIP AND SEND BACK TO USERS SHOWW
    def destroy
        trip = Trip.find_by(id: params[:id])
        trip.destroy
        trip.trip_locations.each do |tl|
            tl.destroy
        end
        redirect_to user_path(trip.user_id)
    end

    private
    # STRONG PARAMS PERMISSIONS
    def trip_params
        params.require(:trip).permit(
            :name,
            locations: [
                :address
            ]
        )
    end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.erb
<% if flash[:error] %>
<h3 style="color:red;"><%= flash[:error] %></h3>
<% end %>
<% flash[:error]="" %>
<table>
<%= form_for(@trip) do |f| %>
<tr>
  <td><label>Trip name:</label></td>
  <td><%= f.text_field :name, placeholder: "(Optional)", autocomplete: "off" %></td>
</tr>
<tr>
  <td><%= f.submit %></td>
</tr>
<% end %>
</table>

app/views/trips/index.erb
Trips for <%= current_user.handle%><br>
<% @trips.each do |t|%>
<%= link_to trip_path(t), trip_path(t) %><br>
<% end %>

app/views/trips/new.erb
<% if flash[:error] %>
<h3 style="color:red;"><%= flash[:error] %></h3>
<% end %>
<% flash[:error]="" %>
<table>
<%= form_for(@trip) do |f| %>
<tr>
  <td><label>Trip name:</label></td>
  <td><%= f.text_field :name, placeholder: "(Optional)", autocomplete: "off" %></td>
</tr>
<tr>
    <%= f.fields_for :locations do |v| %>
    <td><%= v.label "Address:" %></td>
    <td><%= v.text_field :address, list: 'address_list', autocomplete: 'off' %></td>
    <datalist id="address_list">
    <% Location.address_only.order(:address).each do |l| %>
      <option value="<%= l.address %>"></option>
    <% end %>
    </datalist>
    <% end %>
</tr>
<tr>
  <td><%= f.submit %></td>
</tr>
<% end %>
</table>

app/views/trips/show.erb
<% if flash[:error] %>
<h3 style="color:red;"><%= flash[:error] %></h3>
<% end %>
<% flash[:error]="" %>
Details for trip <%= @trip.id %> (<%= @trip.disp_name %>) <%= link_to "Edit", edit_trip_path %><br>
Locations:<br>
<table>
<tr>
<td>Address</td>
<td>Time in</td>
<td>Time out</td>
</tr>
<% @trip.trip_locations.each do |l| %>
<tr>
  <%= form_for l do |tl| %>
  <!--<td><%#= @locations.find(l.location_id).address %></td>-->
  <td><%= l.location.address %></td>
  <td><%= tl.text_field :time_in, size: 5, autocomplete: 'off' %><input type="button" value="🕒" onclick="timeStamp(this.form,'trip_location_time_in','Time in')" /></td>
  <td><%= tl.text_field :time_out, size: 5, autocomplete: 'off' %><input type="button" value="🕒" onclick="timeStamp(this.form,'trip_location_time_out','Time out')" /></td>
  <%= tl.submit :style => "display:none" %>
  <%#= link_to "🗑️", trip_location_path(l.id), method: :delete, data: { confirm: "Are you sure you want to delete this location from your trip?" } %></td>
  <% end %>
  <td><%= form_with(url: trip_location_path(l.id), method: "delete") do |f| %>
    <%= submit_tag("🗑️", :onclick => "return confirm('Are you sure you want to delete this location from your trip?')") %>
  <% end %>
</tr>
<% end %>
<tr>
<td colspan=4>Add a location by address...
</tr>
<tr>
<td colspan=2>
<%= form_for @location do |f| %>
    <%= hidden_field_tag("location[trip_id]", @trip.id) %>
    <%= f.text_field :address, list: 'address_list', autocomplete: 'off' %>
    <datalist id="address_list">
    <% Location.address_only.order(:address).each do |l| %>
      <option value="<%= l.address %>"></option>
    <% end %>
    </datalist>
  </td>
  <td align="right">
  <%= f.submit "Add" %>
<% end %>
</td>
</tr>
</table>
<script>
function timeStamp(src,tgt,type){
	console.log(src);
  time = new Date(); 
  time.setMinutes(time.getMinutes()-time.getTimezoneOffset()); 
  time = time.toISOString().slice(11,16);
	if (confirm("Set `" + type + "` for this location to " + time +"?")){
    src.elements[tgt].value=time;
    src.submit();
  }
}
</script>