config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trip_locations, only: [:create,:update,:destroy]
  # resources :comments  FOR FUTURE USE
  resources :locations, only: [:index,:create]
  # resources :users, only: []

  resources :users, only: [:show,:new,:create] do
  # resources :users do
    resources :trips, only: [:index,:new]
  end
  resources :trips, only: [:index,:show,:edit,:update,:new,:create,:destroy]

  root 'sessions#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post '/logout' => 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/user.rb
class User < ApplicationRecord

    has_many :trips
    has_many :locations
    has_secure_password
    #password is validated thru "has_secure_password"
    validates :handle, :email, presence: true
    validates :email, :handle, uniqueness: true
    #restricts users from signing up with a blank or existing user handle or email

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # SHOW ONLY CURRENT USER SHOW PAGE IF LOGGED IN
  def show
    if logged_in? and 
      if params[:id].to_i == current_user.id
        @user = User.find(params[:id])
      else
        flash[:error] = "User not authorized to other user resources."
        redirect_to "/"
      end
    else
        flash[:error] = "Please log in to use TripTracker."
        redirect_to "/"
    end
end

  # BUILD INSTANCE FOR NEW USER PAGE
  def new
    @user = User.new
  end

  # CREATE NEW USER
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "User signup failed: #{@user.errors.full_messages.to_sentence}"
      render :new 
    end
  end

  # STRONG PARAMS PERMISSIONS
  private
  def user_params
    params.require(:user).permit(:handle, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.erb
<% if flash[:error] %>
<h3 style="color:red;"><%= flash[:error] %></h3>
<% end %>
<% flash[:error]="" %>
<h1>Sign up as a new TripTracker user.</h1>
<%= form_for(@user) do |f| %>
  <label>Handle or Nickname:</label>
  <%= f.text_field :handle %><br>
  <label>Email:</label>
  <%= f.text_field :email %><br>
  <label>Password:</label>
  <%= f.password_field :password %><br>
  <%= f.submit "Sign up"%> or <a href="/login">Log in</a>
<% end %> 

app/views/users/show.erb
<% if flash[:error] %>
<h3 style="color:red;"><%= flash[:error] %></h3>
<% end %>
<% flash[:error]="" %>
Handle: <%= @user.handle %><br>
Email: <%= @user.email %><br>
Trips: <%= @user.trips.count %><br>
<table>
<tr>
<td>Trip ID</td>
<td>Name</td>
<td>Stops</td>
</tr>
<% @user.trips.order("id desc").each do |t|%>
<tr>
<td align="center"><%= t.id %></td>
<td><%= link_to t.disp_name, trip_path(t) %></td>
<td align="center"><%= t.locations.size%></td>
  <td><%= form_with(url: trip_path(t.id), method: "delete") do |f| %>
    <%= submit_tag("🗑️", :onclick => "return confirm('Are you sure you want to delete this trip?')") %>
  <% end %>

<%#= link_to "🗑️", trip_path(t.id), method: :delete, data: { confirm: "Are you sure you want to delete this trip?" } %></td>
</tr>
<% end %>
</table>

